# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\n\n\x08\x65mptyReq\"\x18\n\x07Request\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1e\n\x08Response\x12\x12\n\nbranchName\x18\x01 \x01(\t\"\'\n\x11\x41llBranchResponse\x12\x12\n\nbranchName\x18\x01 \x01(\t2d\n\rBranchService\x12 \n\tgetBranch\x12\x08.Request\x1a\t.Response\x12\x31\n\x0egetAllBranches\x12\t.emptyReq\x1a\x12.AllBranchResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYREQ._serialized_start=14
  _EMPTYREQ._serialized_end=24
  _REQUEST._serialized_start=26
  _REQUEST._serialized_end=50
  _RESPONSE._serialized_start=52
  _RESPONSE._serialized_end=82
  _ALLBRANCHRESPONSE._serialized_start=84
  _ALLBRANCHRESPONSE._serialized_end=123
  _BRANCHSERVICE._serialized_start=125
  _BRANCHSERVICE._serialized_end=225
# @@protoc_insertion_point(module_scope)
