# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\x18\n\x07Request\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1e\n\x08Response\x12\x12\n\nbranchName\x18\x01 \x01(\t21\n\rBranchService\x12 \n\tgetBranch\x12\x08.Request\x1a\t.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=14
  _REQUEST._serialized_end=38
  _RESPONSE._serialized_start=40
  _RESPONSE._serialized_end=70
  _BRANCHSERVICE._serialized_start=72
  _BRANCHSERVICE._serialized_end=121
# @@protoc_insertion_point(module_scope)
